### PR TITLE
fix html preview rendering in tracy panel

### LINKED ISSUE #29: HTML preview displays escaped HTML tags as noescapes
Even if HTML tags are escaped by latte, in nextras mail panel you see proper layout, but in real mail client you see escaped HTML tags instead of HTML formatted layout.

### PR DESCRIPTION
**Pull request by zraly**
This fixes HTML preview rendering in the Tracy panel.

Problem:
- some emails were shown as source text in "Preview HTML" even though the email contained a valid `text/html` part

What changed:
- switched preview generation to use a dedicated `previewHtml` filter
- extract HTML robustly from MIME parts (with decoding)
- keep "Open" and "Preview HTML" rendering consistent
- added regression tests

Fixes #29

### CODE REVIEW

File: src/MailPanel.php [hunk 1]
```diff
@@ -135,29 +139,103 @@ private function getLatte(): Latte\Engine
 			});
 
 			$this->latte->addFilter('plainText', function (MimePart $part) {
```
Comment (hrach) [inline src/MailPanel.php:141]: Is this filter used anywhere now?

File: src/MailPanel.php [hunk 2]
```diff
@@ -135,29 +139,103 @@ private function getLatte(): Latte\Engine
...
-					}
+				$plainText = $this->findBodyByContentType($part, 'text/plain');
+				if ($plainText !== null) {
+					return $plainText;
+				}
+
+				return $this->decodeBody($part);
+			});
+
+			$this->latte->addFilter('htmlBody', function (MimePart $part): string {
```
Comment (hrach) [inline src/MailPanel.php]: Same here, is this filter used anywhere?

File: src/MailPanel.php [hunk 3]
```diff
@@ -135,29 +139,103 @@ private function getLatte(): Latte\Engine
...
+
+
+	/**
+	 * @return MimePart[]
+	 */
+	private function getMimePartParts(MimePart $part): array
+	{
+		if ($this->mimePartPartsProperty === null) {
+			$this->mimePartPartsProperty = new \ReflectionProperty(MimePart::class, 'parts');
+			$this->mimePartPartsProperty->setAccessible(true);
```
Comment (hrach) [inline src/MailPanel.php]: This triggers warning on PHP 8.5

File: src/MailPanel.php (hunk 1 above)
Comment (zraly) [reply src/MailPanel.php:141]: it's still used in [MailPanel.latte](https://github.com/nextras/mail-panel/blob/4ba26ad6528982952e6dc0b2b4de15c976693735/src/MailPanel.latte#L107) for the "Preview TXT"

File: src/MailPanel.php (hunk 2 above)
Comment (zraly) [reply src/MailPanel.php]: No, htmlBody is no longer used after this refactor, so I’ll remove the filter from this PR.

File: src/MailPanel.php (hunk 3 above)
Comment (zraly) [reply src/MailPanel.php]: Thanks. I’ll keep setAccessible(true) only for PHP < 8.1, so older versions still work and PHP 8.5 won’t emit deprecation warnings.

**Review by zraly — COMMENTED** [review]
Addressed in 10f0f88. Could you please re-review?

**Comment by hrach** [comment]
thx!
